### ISSUE TITLE
Passphrase is required on a first boot

### ISSUE THREAD

**Issue by Tibitt** [mathew-dennis/device_kenzo_halium9#3]
even if i wipe data, after booting first time, os requests passphrase after filling devicename, region and other setup blanks

**Comment by mathew-dennis** [comment]
The passphrase is "a" .It is hard-coded when creating the flashable zip . The only way to fix it is to move to ubports installer.That need a bit of work.will look into it if Kenzo can be migrated to 20.04 rootfs ( currently Kenzo can't handle 20.04) .
